# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk/auction/v1/genesis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from amino import amino_pb2 as amino_dot_amino__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1csdk/auction/v1/genesis.proto\x12\x0esdk.auction.v1\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x11\x61mino/amino.proto\x1a\x19\x63osmos_proto/cosmos.proto\"D\n\x0cGenesisState\x12\x34\n\x06params\x18\x01 \x01(\x0b\x32\x16.sdk.auction.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\"\xb5\x03\n\x06Params\x12&\n\x0fmax_bundle_size\x18\x01 \x01(\rR\rmaxBundleSize\x12\x34\n\x16\x65scrow_account_address\x18\x02 \x01(\x0cR\x14\x65scrowAccountAddress\x12\x45\n\x0breserve_fee\x18\x03 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\nreserveFee\x12P\n\x11min_bid_increment\x18\x04 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x0fminBidIncrement\x12\x38\n\x18\x66ront_running_protection\x18\x05 \x01(\x08R\x16\x66rontRunningProtection\x12Y\n\x0cproposer_fee\x18\x06 \x01(\tB6\xc8\xde\x1f\x00\xda\xde\x1f\x1b\x63osmossdk.io/math.LegacyDec\xd2\xb4-\ncosmos.Dec\xa8\xe7\xb0*\x01R\x0bproposerFee:\x1f\x8a\xe7\xb0*\x1a\x62lock-sdk/x/auction/ParamsB/Z-github.com/skip-mev/block-sdk/x/auction/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sdk.auction.v1.genesis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-github.com/skip-mev/block-sdk/x/auction/types'
  _GENESISSTATE.fields_by_name['params']._options = None
  _GENESISSTATE.fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _PARAMS.fields_by_name['reserve_fee']._options = None
  _PARAMS.fields_by_name['reserve_fee']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _PARAMS.fields_by_name['min_bid_increment']._options = None
  _PARAMS.fields_by_name['min_bid_increment']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _PARAMS.fields_by_name['proposer_fee']._options = None
  _PARAMS.fields_by_name['proposer_fee']._serialized_options = b'\310\336\037\000\332\336\037\033cosmossdk.io/math.LegacyDec\322\264-\ncosmos.Dec\250\347\260*\001'
  _PARAMS._options = None
  _PARAMS._serialized_options = b'\212\347\260*\032block-sdk/x/auction/Params'
  _globals['_GENESISSTATE']._serialized_start=148
  _globals['_GENESISSTATE']._serialized_end=216
  _globals['_PARAMS']._serialized_start=219
  _globals['_PARAMS']._serialized_end=656
# @@protoc_insertion_point(module_scope)
