# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk/auction/v1/query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from cosmos.query.v1 import query_pb2 as cosmos_dot_query_dot_v1_dot_query__pb2
from skip_types.sdk.auction.v1 import genesis_pb2 as sdk_dot_auction_dot_v1_dot_genesis__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1asdk/auction/v1/query.proto\x12\x0esdk.auction.v1\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1b\x63osmos/query/v1/query.proto\x1a\x1csdk/auction/v1/genesis.proto\"\x14\n\x12QueryParamsRequest\"K\n\x13QueryParamsResponse\x12\x34\n\x06params\x18\x01 \x01(\x0b\x32\x16.sdk.auction.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params2\x85\x01\n\x05Query\x12|\n\x06Params\x12\".sdk.auction.v1.QueryParamsRequest\x1a#.sdk.auction.v1.QueryParamsResponse\")\x88\xe7\xb0*\x01\x82\xd3\xe4\x93\x02\x1e\x12\x1c/block-sdk/auction/v1/paramsB/Z-github.com/skip-mev/block-sdk/x/auction/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sdk.auction.v1.query_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-github.com/skip-mev/block-sdk/x/auction/types'
  _QUERYPARAMSRESPONSE.fields_by_name['params']._options = None
  _QUERYPARAMSRESPONSE.fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _QUERY.methods_by_name['Params']._options = None
  _QUERY.methods_by_name['Params']._serialized_options = b'\210\347\260*\001\202\323\344\223\002\036\022\034/block-sdk/auction/v1/params'
  _globals['_QUERYPARAMSREQUEST']._serialized_start=157
  _globals['_QUERYPARAMSREQUEST']._serialized_end=177
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=179
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=254
  _globals['_QUERY']._serialized_start=257
  _globals['_QUERY']._serialized_end=390
# @@protoc_insertion_point(module_scope)
