# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk/auction/v1/tx.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from sdk.auction.v1 import genesis_pb2 as sdk_dot_auction_dot_v1_dot_genesis__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17sdk/auction/v1/tx.proto\x12\x0esdk.auction.v1\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x1csdk/auction/v1/genesis.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x17\x63osmos/msg/v1/msg.proto\"\xd4\x01\n\rMsgAuctionBid\x12\x30\n\x06\x62idder\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x06\x62idder\x12\x36\n\x03\x62id\x18\x02 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x03\x62id\x12\"\n\x0ctransactions\x18\x03 \x03(\x0cR\x0ctransactions:5\xe8\xa0\x1f\x00\x82\xe7\xb0*\x06\x62idder\x8a\xe7\xb0*!block-sdk/x/auction/MsgAuctionBid\"\x17\n\x15MsgAuctionBidResponse\"\xbb\x01\n\x0fMsgUpdateParams\x12\x36\n\tauthority\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\tauthority\x12\x34\n\x06params\x18\x02 \x01(\x0b\x32\x16.sdk.auction.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params::\xe8\xa0\x1f\x00\x82\xe7\xb0*\tauthority\x8a\xe7\xb0*#block-sdk/x/auction/MsgUpdateParams\"\x19\n\x17MsgUpdateParamsResponse2\xdd\x01\n\x03Msg\x12u\n\nAuctionBid\x12\x1d.sdk.auction.v1.MsgAuctionBid\x1a%.sdk.auction.v1.MsgAuctionBidResponse\"!\x82\xd3\xe4\x93\x02\x1b\"\x19/block-sdk/auction/v1/bid\x12X\n\x0cUpdateParams\x12\x1f.sdk.auction.v1.MsgUpdateParams\x1a\'.sdk.auction.v1.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01\x42/Z-github.com/skip-mev/block-sdk/x/auction/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sdk.auction.v1.tx_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-github.com/skip-mev/block-sdk/x/auction/types'
  _MSGAUCTIONBID.fields_by_name['bidder']._options = None
  _MSGAUCTIONBID.fields_by_name['bidder']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _MSGAUCTIONBID.fields_by_name['bid']._options = None
  _MSGAUCTIONBID.fields_by_name['bid']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _MSGAUCTIONBID._options = None
  _MSGAUCTIONBID._serialized_options = b'\350\240\037\000\202\347\260*\006bidder\212\347\260*!block-sdk/x/auction/MsgAuctionBid'
  _MSGUPDATEPARAMS.fields_by_name['authority']._options = None
  _MSGUPDATEPARAMS.fields_by_name['authority']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _MSGUPDATEPARAMS.fields_by_name['params']._options = None
  _MSGUPDATEPARAMS.fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _MSGUPDATEPARAMS._options = None
  _MSGUPDATEPARAMS._serialized_options = b'\350\240\037\000\202\347\260*\tauthority\212\347\260*#block-sdk/x/auction/MsgUpdateParams'
  _MSG._options = None
  _MSG._serialized_options = b'\200\347\260*\001'
  _MSG.methods_by_name['AuctionBid']._options = None
  _MSG.methods_by_name['AuctionBid']._serialized_options = b'\202\323\344\223\002\033\"\031/block-sdk/auction/v1/bid'
  _globals['_MSGAUCTIONBID']._serialized_start=229
  _globals['_MSGAUCTIONBID']._serialized_end=441
  _globals['_MSGAUCTIONBIDRESPONSE']._serialized_start=443
  _globals['_MSGAUCTIONBIDRESPONSE']._serialized_end=466
  _globals['_MSGUPDATEPARAMS']._serialized_start=469
  _globals['_MSGUPDATEPARAMS']._serialized_end=656
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_start=658
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_end=683
  _globals['_MSG']._serialized_start=686
  _globals['_MSG']._serialized_end=907
# @@protoc_insertion_point(module_scope)
